### ISSUE TITLE
Bug encountered while creating a container.

### ISSUE THREAD

**Issue by Scorp3373** [sireproject/sireproject.github.io#6]
`docker@default:~$ docker@default:~$ docker run --rm -it -v /c/Anurag/<path>/Docu
ments/sire:/sire -v $(which docker):$(which docker) -v /var/run/docker.sock:/var
/run/docker.sock --name sire ubuntu bash`

While creating my first container using above code, I get this error:

`-sh: can't open path: no such file`
`-sh: docker@default:~$: not found`

How do I resolve it? Thanks!

**Comment by braderhart** [comment]
This is because you need to only copy & paste the commands to the right of the $ sign, eg:

`docker@default:~$ docker run --rm -it -v /c/Users/<path>/Documents/sire:/sire -v $(which docker):$(which docker) -v /var/run/docker.sock:/var /run/docker.sock --name sire ubuntu bash`
